export class Complain {
    
    constructor() {
    }
  public complaint_no:string;
  public complaintid:string;
  public complaint_date:string;
  public doctype:string;
  public nameofcomplainer:string;
  public desofcomplnr:string;
  public contnumber:string;
  public email:string;
  public eventdate:string;
  public description:string;
  public lotno:string;
  public serialno:string;
  public srnoequipment:string;
  public contracttype:string;
  public invoiceno:string;
  public invoicedate:string;
  public errorcode:string;
  public dealername:string;
  public installationdate:string;
  public skucode:string;
  public skuname:string;
  public brandname:string;
  public producttobereturn:string;
  public custname:string;
  public add1:string;
  public add2:string;
  public add3:string;
  public pincode:string;
  public area:string;
  public city:string;
  public state:string;
  public country:string;
  public appcomplaint:string;
  public assigntoservvendor:string;
  public newdealername:string;
  public salesrepresentative:string;
  public servicemanager:string;
  public business:string;
  public serviceengname:string;
  public serviceengcontact:string;
  public visitdate:string;
  public servicevendorremark:string;
  public assigntoservmg:string
  public problem_observed:string;
  public field_visit_remarks:string;
  public proposed_action:string
  public dealer_billing_address:string;
  public dealer_shipping_address:string;
  public assign_to:string;
  public spare_SKUCode:string;
  public quantity:string;
  public dealer_name:string;
  public cop_sales_order_reference:string;
  public spare_received_date:string;
  public repair_report:string;
  public complaint_status:string;
  public completion_date:string;
  public replaced_spare_part_serialNo:string;
  public service_attended:string;
  public defective_sparePart:string
  public defective_spare_part_no:string
  public def_spare_docket_no:string;
  public def_spare_courier:string;
  public def_spare_sent_date:string;
  public spare_install_closed:string;
  public service_manager_remark:string;
  public smart_solve_ref_no:string;
  public defective_spare_part_received_date:string;
  public final_closure:string;
  public Appect:string;
  public reject:string;
  public servicevendor:string;
  public closureatfield:string;
  public imagebase64:any;
  public sparerequestid:any;
  public orderid:string;
  public sapreskuid:string;
  public qty:string;
  public sparerequiredid:string;
  public file_type:string;
  public file_selected_uri:string;
  public activity:string;
}